### ISSUE TITLE
get Message "Failed to set up: Import error"

### ISSUE THREAD

**Issue by dibi73** [RJArmitage/rfxtrx-state#1]
I habe coplied the Files as described but get the errormessage "Failed to set up: Import error" when i look to Configuration -> Integrations.
I am using supervisor-2021.10.8 on Home Assistant OS 6.6

**Comment by RJArmitage** [comment]
Looks like the imports have changed. I’ll upload a revised version in a couple of hours

**Comment by RJArmitage** [comment]
Please try with the latest release and let me know how you get on

**Comment by RJArmitage** [comment]
Did the new version of the software fix your issue? You will likely need to update to v1.2.0 for Home Assistant 2021.12

**Comment by RJArmitage** [comment]
Closing due to no feedback
